apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-app-rc
  lables: 
    app: my-app
    type: front-end
spec: 
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: front-ent
    containers:
    - name: nginx-container
      image: nginx
replicas: 3
