apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-rs
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: my-app-pod
      labels:
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
